#!/bin/bash

REFINEDC_PATH="$( builtin cd "$( dirname "${BASH_SOURCE[0]}" )/.." >/dev/null 2>&1 && pwd )"

eval "$(builtin cd "${REFINEDC_PATH}" && opam env)"

# Check if Cerberus needs to be compiled (not enough to just exec here).
if [ ! -d "${REFINEDC_PATH}/_build" ]; then
   echo -n "Compiling [rcgen]... "
   dune build --no-print-directory --root "${REFINEDC_PATH}" 2> /dev/null ||
      ( echo "Error..." && return 1 )
   echo "Done."
fi

# We forward the arguments to the actual command.
dune exec --no-print-directory --root "${REFINEDC_PATH}" -- rcgen "$@"
